# GitHub Funding Configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Buy Me a Coffee support
# buy_me_coffee: username

# GitHub Sponsors
github: horsto

